
services:
  api:
    image: api
    container_name: api
    build:
      context: .
      target: app
    ports:
      - 8080:8080
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8080"]
 